#!/usr/bin/env python

Import("env")

# default values, adapt them to your setup
default_library_name = "libgdexample"
default_target_path = "demo/bin/"

# Local dependency paths, adapt them to your setup
cpp_bindings_path = "../"
# cpp_bindings_path = "godot-cpp/"
godot_headers_path = cpp_bindings_path + "godot-headers/"

opts = Variables([], ARGUMENTS)

# Define our options
opts.Add(
    PathVariable("target_path", "The path where the lib is installed.", default_target_path, PathVariable.PathAccept)
)
opts.Add(PathVariable("target_name", "The library name.", default_library_name, PathVariable.PathAccept))

# Updates the environment with the option variables.
opts.Update(env)
# Generates help for the -h scons option.
Help(opts.GenerateHelpText(env))

# For the reference:
# - CCFLAGS are compilation flags shared between C and C++
# - CFLAGS are for C-specific compilation flags
# - CXXFLAGS are for C++-specific compilation flags
# - CPPFLAGS are for pre-processor flags
# - CPPDEFINES are for pre-processor defines
# - LINKFLAGS are for linking flags

# tweak this if you want to use different folders, or more folders, to store your source code in.
env.Append(CPPPATH=["src/"])
sources = Glob("src/*.cpp")

target_name = "{}{}".format(env["target_name"], env["SHLIBSUFFIX"])
library = env.SharedLibrary(target=env["target_path"] + target_name, source=sources)

Default(library)
